
version: '3'

services:
  db:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: user_stories
      MYSQL_USER: root
      MYSQL_PASSWORD: password
    ports:
      - "9906:3306"
  web:
    image: php:latest
    container_name: php_web
    depends_on:
      - db
    volumes:
      - ./php/:/var/www/user_stories/
    ports:
      - "8100:80"
    stdin_open: true
    tty: true